config/routes.rb
Kanri::Application.routes.draw do

  get 'admin' => 'admin#index'
  controller :sessions do
    get 'login' => :new
    post 'login' => :create
    delete 'logout' => :destroy
  end

  get "admin/index"

  get "sessions/new"

  get "sessions/create"

  get "sessions/destroy"

  get "home/index"

  resources :schedules
  resources :users
  get "/users/index"
  get "/schedules/index"

end

app/models/schedule.rb
class Schedule < ActiveRecord::Base
  attr_accessible :being, :finish, :start, :title, :user_id
  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :attached, :mail, :name, :turnUp, :password
  has_many :schedules
  validates :name, presence: true, uniqueness: true
  has_secure_password
end

app/controllers/.#users_controller.rb
kazuto@ubuntu.25605:1364634533

app/controllers/admin_controller.rb
class AdminController < ApplicationController
  def index
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  before_filter :authorize

  private
    def authorize
      unless User.find_by_id(session[:user_id])
        redirect_to login_url, notice: "Please login"
      end
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  skip_before_filter :authorize  

  def index
  end
end

app/controllers/schedules_controller.rb
class SchedulesController < ApplicationController

  # GET /schedules
  # GET /schedules.json
  def index
   @schedules = Schedule.order(params[:sort])
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @schedules }
    end
  end
  # GET /schedules/1
  # GET /schedules/1.json
  def show
    @schedule = Schedule.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @schedule }
    end
  end

  # GET /schedules/new
  # GET /schedules/new.json
  def new
    @schedule = Schedule.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @schedule }
    end
  end

  # GET /schedules/1/edit
  def edit
    @schedule = Schedule.find(params[:id])
  end

  # POST /schedules
  # POST /schedules.json
  def create
    @schedule = Schedule.new(params[:schedule])

    respond_to do |format|
      if @schedule.save
        format.html { redirect_to @schedule, notice: 'Schedule was successfully created.' }
        format.json { render json: @schedule, status: :created, location: @schedule }
      else
        format.html { render action: "new" }
        format.json { render json: @schedule.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /schedules/1
  # PUT /schedules/1.json
  def update
    @schedule = Schedule.find(params[:id])

    respond_to do |format|
      if @schedule.update_attributes(params[:schedule])
        format.html { redirect_to @schedule, notice: 'Schedule was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @schedule.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /schedules/1
  # DELETE /schedules/1.json
  def destroy
    @schedule = Schedule.find(params[:id])
    @schedule.destroy

    respond_to do |format|
      format.html { redirect_to schedules_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_before_filter :authorize 
  def new
  end

  def create
    user = User.find_by_name(params[:name])
    if user and user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to admin_url
    else
      redirect_to login_url, alert: "error"
    end
    
  end

  def destroy
    session[:user_id] = nil;
    redirect_to users_url
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  # GET /users
  # GET /users.json

  setup do
    @input_attributes = {
      name: "sam",
      mail: "sam@samsam.com",
      attached: "UEC",
      turnUp: true,
      password: "private",
      password: "private"
    }
    @user = users(:one)
  end

  test "should get index" do
    get :index
    assert_response :success
    assert_not_nil assigns(:users)
  end

  test "should get new" do
    get :new
    assert_response :success
  end

  test "should create user" do
    assert_difference('User.count') do
      post :create, user: @input_attributes
    end

    assert_redirected_to users_path
  end

  test "should show user" do
    get :show, id: @user
    assert_response :success
  end

  test "should get edit" do
    get :edit, id: @user
    assert_response :success
  end

  test "should update user" do
    put :update, id: @user.to_param, user: @input_attributes
    assert_redirected_to users_path
  end

  test "should destroy user" do
    assert_difference('User.count', -1) do
      delete :destroy, id: @user
    end

    assert_redirected_to users_path
  end

  def index
    @users = User.order(params[:sort])
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @users }
    end
  end

  # GET /users/1
  # GET /users/1.json
  def show
    @user = User.find(params[:id])
    @schedule = Schedule.find(:all)
   #  @schedule = Schedule.find(:condition ,[:whose ==:@user.id])
   #  unless schedule then
   #  end
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/new
  # GET /users/new.json
  def new
    @user = User.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/1/edit
  def edit
    @user = User.find(params[:id])
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(params[:user])

    respond_to do |format|
      if @user.save
        format.html { redirect_to users_url, notice: 'User was successfully created.' }
        format.json { render json: @user, status: :created, location: @user }
      else
        format.html { render action: "new" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /users/1
  # PUT /users/1.json
  def update
    @user = User.find(params[:id])

    respond_to do |format|
      if @user.update_attributes(params[:user])
        format.html { redirect_to users_url, notice: 'User was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user = User.find(params[:id])
    @user.destroy

    respond_to do |format|
      format.html { redirect_to users_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/schedules_helper.rb
module SchedulesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/index.html.erb
<h1>Admin#index</h1>
<p>Find me in app/views/admin/index.html.erb</p>

app/views/home/index.html.erb
<h1>ログインページ</h1>
<ul>
  <li><a href="#">ログイン</a></li>
  <li><a href="#">ログアウト</a></li>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Kanri</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>



</body>
</html>

app/views/schedules/_form.html.erb
<%= form_for(@schedule) do |f| %>
  <% if @schedule.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@schedule.errors.count, "error") %> prohibited this schedule from being saved:</h2>

      <ul>
      <% @schedule.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :start %><br />
    <%= f.datetime_select :start, :default => Time.now + 1.day %>
  </div>
  <div class="field">
    <%= f.label :finish %><br />
    <%= f.datetime_select :finish, :default => Time.now + 1.day %>
  </div>
  <div class="field">
    <%= f.label :being %><br />
    <%= f.check_box :being %>
  </div>
  <div class="field">
    <%= f.label :user_id %><br />
    <%= f.number_field :user_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/schedules/edit.html.erb
<h1>Editing schedule</h1>

<%= render 'form' %>

<%= link_to 'Show', @schedule %> |
<%= link_to 'Back', schedules_path %>

app/views/schedules/index.html.erb
<h1>社員スケジュール</h1>

<table class='scaffold_table'><!--　CSS指定の方法 -->
  <tr>
    <th><%= link_to "スケジュール名", sort: "title" %></th>
    <th><%= link_to "開始時刻", sort: "start" %></th>
    <th><%= link_to "終了時刻", sort: "finish" %></th>
    <th><%= link_to "状態", sort: "being" %></th>
    <th><%= link_to "ユーザ", sort: "user_id" %></th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @schedules.each do |schedule| %>
  <tr>
    <td><%= schedule.title %></td>
    <td><%= schedule.start.year %>年<%= schedule.start.month %>月<%= schedule.start.day %>日<%= schedule.start.hour %>:<%= schedule.start.min %></td>
    <td><%= schedule.finish.year %>年<%= schedule.finish.month %>月<%= schedule.finish.day %>日<%= schedule.finish.hour %>:<%= schedule.finish.min %></td>
    <td><%= if schedule.being == true then "実行中" else "待機中" end %></td>
    <td><%= schedule.user_id %></td>
    <td><%= link_to 'スケジュール個別ページ', schedule %></td>
    <td><%= link_to 'スケジュール管理', edit_schedule_path(schedule) %></td>
    <td><%= link_to 'スケジュール消去', schedule, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'スケジュールを追加', new_schedule_path %>
<%= link_to '社員一覧', '/users' %>

app/views/schedules/new.html.erb
<h1>New schedule</h1>

<%= render 'form' %>

<%= link_to 'スケジュール一覧に戻る', schedules_path %>

app/views/schedules/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>スケジュール名:</b>
  <%= @schedule.title %>
</p>

<p>
  <b>開始時刻:</b>
  <%= @schedule.start %>
</p>

<p>
  <b>終了時刻:</b>
  <%= @schedule.finish %>
</p>

<p>
  <b>状態:</b>
  <%= if @schedule.being == true then "実行中" end %>
</p>

<p>
  <b>Whose:</b>
  <%= @schedule.user_id %>
</p>


<%= link_to 'このスケジュールを編集', edit_schedule_path(@schedule) %> |
<%= link_to 'スケジュール一覧に戻る', schedules_path %>

app/views/users/.#show.html.erb
kazuto@ubuntu.2975:1364554622

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
<legend>ユーザ情報の入力</legend>

  <div class="field">
    <%= f.label :名前 %><br />
    <%= f.text_field :name, size: 40 %>
  </div>
  <div class="field">
    <%= f.label :メールアドレス %><br />
    <%= f.text_field :mail %>
  </div>
  <div class="field">
    <%= f.label :所属 %><br />
    <%= f.text_field :attached %>
  </div>
  <div class="field">
    <%= f.label :出社状態 %><br />
    <%= f.check_box :turnUp %>
  </div>
  <div class="field">
    <%= f.label :パスワード %><br />
    <%= f.password_field :password, size: 40 %>
  </div>
  <div class="field">
    <%= f.label :パスワードの確認 %><br />
    <%= f.password_field :password_confirmaion, size: 40 %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<h1>社員リスト</h1>

  <% if notice %>
  <p id="notice"><%= notice %></p>
  <% end %>


<table class='scaffold_table'>
  <tr>
    <th><%= link_to "ID", sort: "id" %></th>
    <th><%= link_to "名前", sort: "name" %></th>
    <th><%= link_to "連絡先(メールアドレス,電話番号)", sort: "mail" %></th>
    <th><%= link_to "所属", sort: "attached" %></th>
    <th><%= link_to "出社状態", sort: "turnUp" %></th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @users.each do |user| %>
  <tr>
    <td><%= user.id %></td>
    <td><%= user.name %></td>
    <td><%= user.mail %></td>
    <td><%= user.attached %></td>
    <td><%= if user.turnUp == true then "しています" else "していません" end %></td>
    <td><%= link_to 'ユーザーページ', user %></td>
    <td><%= link_to 'ユーザー情報変更', edit_user_path(user) %></td>
    <td><%= link_to 'ユーザ情報削除', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'メンバーを追加する', new_user_path %>
<%= link_to 'スケジュール一覧', '/schedules' %>

app/views/users/new.html.erb
<h1>社員情報の追加</h1>

<%= render 'form' %>

<%= link_to '社員一覧に戻る', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>名前:</b>
  <%= @user.name %>
</p>

<p>
  <b>メールアドレス:</b>
  <%= @user.mail %>
</p>

<p>
  <b>所属:</b>
  <%= @user.attached %>
</p>

<p>
  <b>出社状態:</b>
  <%= @user.turnUp %>
</p>


<table class='scaffold_table'><!--　CSS指定の方法 -->
  <tr>
    <th>スケジュール名</th>
    <th>開始時刻</th>
    <th>終了時刻</th>
    <th>状態</th>
  </tr>

  <% if @user.schedules %>
    <% for det in @user.schedules #ここはmodelに合わせてschedules %>
<tr>
    <td><%= det.title %></td>
     <td><%= det.start.year %>年<%= det.start.month %>月<%= det.start.day %>日<%= det.start.hour %>:<%= det.start.min %></td>
      <td><%= det.finish.year %>年<%= det.finish.month %>月<%= det.finish.day %>日<%= det.finish.hour %>:<%= det.finish.min %></td>
    <td><%= if det.being == true then "実行中" else "待機中" end %></td>
</td>
    <% end %>
  <% end %>
</table>

<%= link_to 'ユーザ情報変更', edit_user_path(@user) %> |
<%= link_to '社員一覧へ', users_path %> |
<%= link_to 'スケジュール一覧', '/schedules' %>